"bad PR" = "- bad PR, pay attention to the following advises: \\n"
checkStandup = "Good standup, post it to the group!"
closingPart = "I will kick you from the group if you miss 3 standups. In case of any unexpected behaviour DM @anatoliyfedorenko"
"create standuper failed" = "Could not add you to standup team"
failedLeaveStanupers = "Could not remove you from standup team"
failedRecognizeTZ = "Failed to recognize new TZ you entered, double check the tz name and try again"
failedRemoveStandupDeadline = "Could not remove standup deadline"
failedUpdateStandupDeadline = "Could not edit standup deadline"
failedUpdateTZ = "Failed to update Timezone"
"good PR" = "- good PR, review indeed needed!"
greatStandup = "Standup accepted and it looks awesome!"
leaveStanupers = "You no longer have to submit standups, thanks for all your standups and messages"
noStandupDeadline = "Standup deadline is not set"
"not standup" = "Seems like this is not a standup, double check keywords for errors \\n\\n"
notStanduper = "You do not standup yet"
removeStandupDeadline = "Standup deadline removed"
standupDeadline = "Standup deadline set for everyday at {{.Deadline}} exept weekeds"
standupDeadlinePart = "Submit your standups before, {{.Deadline}}! You do not have to write standups on weekends"
standupUpdated = "Standup was successfully updated!"
standupsCheckPart = "If you would like to validate your standup, direct message me with the text and I can check it to give advises. \\n"
updateStandupDeadline = "Edited standup deadline, new deadline is {{.Deadline}}"
updateTZ = "Group timezone is updated, new TZ is {{.TZ}}"
updateUserTZ = "your timezone is updated, new TZ is {{.TZ}}"
welcomeMessage = "Hello! I will help you to not forget about standups and write them properly. tag @anatoliyfedorenko if you find any bug or unexpected behaiviour :)"
welcomeNoDedline = "Welcome to the standup team, no standup deadline has been setup yet"
welcomePart = "Hello, {{.Intern}}! Welcome to {{.GroupName}}"
welcomeWithDedline = "Welcome to the standup team, please, submit your standups no later than {{.Deadline}}"
youAlreadyStandup = "You already a part of standup team"

[acceptStandupWithAdvises]
few = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
many = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
one = "Standup is accepted, but let me give you one advise: \\n {{.Advises}}"
other = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
two = "Standup is accepted, but let me give you two advises: \\n {{.Advises}}"

[checkStandupWithAdvises]
few = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
many = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
one = "Standup is going to be more usefull with one advise: \\n {{.Advises}}"
other = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
two = "Standup is going to be more usefull with two advises: \\n {{.Advises}}"
