[acceptStandupWithAdvises]
hash = "sha1-900c00a2bbdffbe45361d602a2d8f89f30d0423d"
few = "Стендап принят, но позволь дать несколько советов: "
many = "Стендап принят, но позволь дать советы: "
one = "Стендап принят, но позволь дать один совет: "
two = "Стендап принят, но позволь дать пару советов: "
other = "Стендап принят, но позволь дать несколько советов: "
