["bad PR"]
hash = "sha1-7df112903b8328763bd8fe09d1295fbb4156cd23"
other = "- пересмотри PR, удели внимание следующим советам: \\n"

["good PR"]
hash = "sha1-5379ae28a52e0459744cb0e23f01df2556b87b30"
other = "- хороший PR, можно смотреть!"

["good standup"]
hash = "sha1-a7eb979ca3562c99e48d8f411692b50a29bb7cbf"
other = "Хороший стендап, можно постить в группу!"

["not standup"]
hash = "sha1-241823387c28531a67f9e9d0a29ac62a6d9dd92f"
other = "Кажется это не стендап, перепроверь ключевые слова на ошибки \\n\\n"
