analyzeNoBlockers = "- seems like standups does not contain any prolem or blocker. Remember that problems help us grow. No problems == no development. Dont hesitate to report them"
analyzeNoLinks = "- seems like standups does not contain any links, that means that probably no work was done or no research was conducted. Poor you."
analyzeNoQuestions = "- seems like standups does not contain any questions. Internship is made up of questions, so ask as many as you can!"
analyzeNoSize = "- seems like standups does is either small or too large. Appropriate size is about 80 - 200 words."
analyzeNoTags = "- seems like standups does not contain any tags. If you want your mentors to notice you, tag them right away!"
analyzePRAsignee = "- need to add who is assigned to implement changes to this PR"
analyzePRConflicts = "- no way to merge it. Fix conflicts first"
analyzePRDescription = "- need more words in PR Description field"
analyzePRLinks = "- need to include links on tickets which would be closed by this PR"
analyzePRReviewer = "- no reviewers tagged, please, assign at least one"
analyzePRSize = "- PR contains too much changes. Divide it and resend."
analyzePRWIP = "- PR contains unfinished work, please, finish it and resend the link"
badPR = "- плохой PR, Обрати внимание на советы: \\n"
checkStandup = "Хороший стендап! Можно постить в группу"
closingPart = "I will kick you from the group if you miss 3 standups. In case of any unexpected behaviour DM @anatoliyfedorenko"
createStanduperFailed = "не удалось добавить вас в команду стендаперов"
failedLeaveStanupers = "Не удалось убрать вас из стендаперов"
failedRecognizeTZ = "Failed to recognize new TZ you entered, double check the tz name and try again"
failedRemoveStandupDeadline = "Не удалось убрать крайний срок сдачи стендапов"
failedUpdateStandupDeadline = "Не смог обновить срок сдачи стендапов"
failedUpdateTZ = "Не удалось обновить часовой пояс"
goodPR = "- хороший PR, нужно сделать ревью!"
greatStandup = "Стендап принят и кажется он шикарный!"
helpText = "Список доступных команд:\n\t\t\t/help - Показывает список команд\n\t\t\t/join - Добавляет вас в стендаперы группы\n\t\t\t/show - Показывает кто сдает стендапы в группе\n\t\t\t/leave - Бот перестаёт отслеживать ваши стендапы\n\t\t\t/edit_deadline - Назначить крайний срок сдачи стендапов (форматы: 13:50, 1:50pm)\n\t\t\t/show_deadline - Показывает срок сдачи стендапов\n\t\t\t/group_tz - Изменить часовой пояс группы (по умолчнию: Asia/Bishkek)\n\t\t\t/tz - Изменить часовой пояс стендапера (по умолчанию: Asia/Bishkek)\n\t\t\tС нетерпением жду ваших стендапов! За все мои ошибки отвечает @anatoliyfedorenko
leaveStanupers = "Вам больше не нужно сдавать стендапы, спасибо за все ваши сообщения!"
noProblemsMention = "- нет ключевых слов блока 'проблемы' {{.Keywords}}"
noStandupDeadline = "Крайний срок сдачи стендапов не установлен"
noTodayMention = "- нет ключевых слов блока 'сегодня': {{.Keywords}}"
noYesterdayMention = "- нет ключевых слов блока 'вчера': {{.Keywords}}"
notStandup = "Кажется это вообще не стендап, перепроверьте ключевые слова \\n\\n"
notStanduper = "Вы еще не стендапите"
notifyNonReporters = "Внимение, {{.Intern}}! ты только что пропустил дедлайн! Отправь стендап как можно скорее и не подводи команду! осталось пропусков: {{.Skips}} \\n\\n"
removeStandupDeadline = "Крайний срок сдачи стендапов отменён"
standupDeadline = "Пишите стендапы каждый день до {{.Deadline}} кроме выходных"
standupDeadlinePart = "Сдавайте стендапы до {{.Deadline}}! Можете не писать стендапы на выходных"
standupUpdated = "Стендап успешно обновлен"
standupsCheckPart = "Если хотите узнать приму ли я стендап или увидеть советы по его улучшению, напишите мне текст в личные сообщения. \\n"
updateStandupDeadline = "Крайний срок сдачи стендапов изменён на {{.Deadline}}"
updateTZ = "Часовой пояс группы обновлен на {{.TZ}}"
updateUserTZ = "ваш часовой пояс обновлен на {{.TZ}}"
warnNonReporters = "Attention, {{.Intern}} {{.Warn}} minutes till deadline, submit standups ASAP. {{.Skips}} skips left \\n\\n"
welcomeMessage = "Приветствую! Я буду помогать вам не забывать о стендапах и улучшать их качество и пользу. За все мои проблемы в ответе @anatoliyfedorenko :)"
welcomeNoDedline = "Добро пожаловать в стендап команду, дедлайна пока не установлено"
welcomePart = "Привет, {{.Intern}}! Добро пожаловать в {{.GroupName}}"
welcomeWithDedline = "Добро пожаловать в команду стендаперов. Пишите стендапы до {{.Deadline}}"
youAlreadyStandup = "Вы уже в команде стендаперов"

[acceptStandupWithAdvises]
few = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
many = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
one = "Стендап принят, но дам один совет: \\n {{.Advises}}"
other = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
two = "Стендап принят, но дам парочку советов: \\n {{.Advises}}"

[checkStandupWithAdvises]
few = "Дам несколько советов по стендапу \\n {{.Advises}}"
many = "Дам несколько советов по стендапу \\n {{.Advises}}"
one = "Дам один совет по стендапу: \\n {{.Advises}}"
other = "Дам несколько советов по стендапу \\n {{.Advises}}"
two = "Дам пару советов по стендапу: \\n {{.Advises}}"
