[showStandupers]
few = "{{.Standupers}} submit standups in the team"
hash = "sha1-7c1b080d825ac604d70c078f362aea96a5ca37d0"
many = "{{.Standupers}} submit standups in the team"
one = "{{.Standupers}} submit standups in the team"
other = "{{.Standupers}} submit standups in the team"
