analyzeNoBlockers = "- Кажется в стендапе нет или мало проблем. Проблемы и всё, что мешает это показатель роста. Если их нет, это плохо. не бойся об этом говорить"
analyzeNoLinks = "- Кажется в стендапе нет ни одной ссылки. Желательно отправлять ссылки на PRы либо на изученные ресурсы"
analyzeNoQuestions = "- Кажется в стендапе не задано вопросов. На стажировке надо задавать вопросы, самое лучше место это общий чат и стендапы. Без вопросов нет развития"
analyzeNoSize = "- Подумай над размером стендапа. Напишешь мало - непонятно, грач, без уважения. Много - тяжело читать. Оптимально от 80 до 200 слов"
analyzeNoTags = "- Кажется в стендапе нет тегов. Тегай менторов, чтобы получить их опыт, иначе прогресс будет медленный"
analyzePRAsignee = "- нужно назначить человека, который работает над PRом"
analyzePRConflicts = "- нельзя смержить код в PR, сначала надо решить все конфликты"
analyzePRDescription = "- нужно больше слов в описании к PR"
analyzePRLinks = "- желательно добавить в описание ссылки на задачи, которые закроет этот PR"
analyzePRReviewer = "- нет назначеных на ревью людей, лучше отметить кого-нибудь"
analyzePRSize = "- в PR очень много изменений, попробуй его разделить."
analyzePRWIP = "- PR содержит незавершенную работу, сначала надо закончить её"
badPR = "- плохой PR, Обрати внимание на советы: \\n"
checkStandup = "Хороший стендап! Можно постить в группу"
closingPart = "Я удаляю из группы если пропущено более 3х стендапов. За все мои ошибки отвечает @anatoliyfedorenko"
createStanduperFailed = "не удалось добавить вас в команду стендаперов"
failedLeaveStanupers = "Не удалось убрать вас из стендаперов"
failedRecognizeTZ = "Failed to recognize new TZ you entered, double check the tz name and try again"
failedRemoveStandupDeadline = "Не удалось убрать крайний срок сдачи стендапов"
failedUpdateStandupDeadline = "Не смог обновить срок сдачи стендапов"
failedUpdateTZ = "Не удалось обновить часовой пояс"
goodPR = "- хороший PR, нужно сделать ревью!"
greatStandup = "Стендап принят и кажется он шикарный!"
helpText = "Список доступных команд:\n\t\t\t/help - Показывает список команд\n\t\t\t/join - Добавляет вас в стендаперы группы\n\t\t\t/show - Показывает кто сдает стендапы в группе\n\t\t\t/leave - Бот перестаёт отслеживать ваши стендапы\n\t\t\t/edit_deadline - Назначить крайний срок сдачи стендапов (форматы: 13:50, 1:50pm)\n\t\t\t/show_deadline - Показывает срок сдачи стендапов\n\t\t\t/group_tz - Изменить часовой пояс группы (по умолчнию: Asia/Bishkek)\n\t\t\t/tz - Изменить часовой пояс стендапера (по умолчанию: Asia/Bishkek)\n\t\t\tС нетерпением жду ваших стендапов! За все мои ошибки отвечает @anatoliyfedorenko"
leaveStanupers = "Вам больше не нужно сдавать стендапы, спасибо за все ваши сообщения!"
noProblemsMention = "- нет ключевых слов блока 'проблемы' {{.Keywords}}"
noStandupDeadline = "Крайний срок сдачи стендапов не установлен"
noTodayMention = "- нет ключевых слов блока 'сегодня': {{.Keywords}}"
noYesterdayMention = "- нет ключевых слов блока 'вчера': {{.Keywords}}"
notStandup = "Кажется это вообще не стендап, перепроверьте ключевые слова \\n\\n"
notStanduper = "Вы еще не стендапите"
notifyNonReporters = "Внимение, {{.Intern}}! ты только что пропустил дедлайн! Отправь стендап как можно скорее и не подводи команду! осталось пропусков: {{.Skips}} \\n\\n"
removeStandupDeadline = "Крайний срок сдачи стендапов отменён"
standupDeadline = "Пишите стендапы каждый день до {{.Deadline}} кроме выходных"
standupDeadlinePart = "Сдавайте стендапы до {{.Deadline}}! Можете не писать стендапы на выходных"
standupUpdated = "Стендап успешно обновлен"
standupsCheckPart = "Если хотите узнать приму ли я стендап или увидеть советы по его улучшению, напишите мне текст в личные сообщения. \\n"
updateStandupDeadline = "Крайний срок сдачи стендапов изменён на {{.Deadline}}"
updateTZ = "Часовой пояс группы обновлен на {{.TZ}}"
updateUserTZ = "ваш часовой пояс обновлен на {{.TZ}}"
warnNonReporters = "Внимание, {{.Intern}} осталось {{.Warn}} минут до дедлайна, срочно пиши стендап. Пропусков осталось: {{.Skips}} \\n\\n"
welcomeMessage = "Приветствую! Я буду помогать вам не забывать о стендапах и улучшать их качество и пользу. За все мои проблемы в ответе @anatoliyfedorenko :)"
welcomeNoDedline = "Добро пожаловать в стендап команду, дедлайна пока не установлено"
welcomePart = "Привет, {{.Intern}}! Добро пожаловать в {{.GroupName}}"
welcomeWithDedline = "Добро пожаловать! Жду стендапы от вас до {{.Deadline}} каждый день кроме выходных"
youAlreadyStandup = "Вы уже стендапите"

[acceptStandupWithAdvises]
few = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
many = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
one = "Стендап принят, но дам один совет: \\n {{.Advises}}"
other = "Стендап принят, но дам несколько советов: \\n {{.Advises}}"
two = "Стендап принят, но дам парочку советов: \\n {{.Advises}}"

[checkStandupWithAdvises]
few = "Дам несколько советов по стендапу \\n {{.Advises}}"
many = "Дам несколько советов по стендапу \\n {{.Advises}}"
one = "Дам один совет по стендапу: \\n {{.Advises}}"
other = "Дам несколько советов по стендапу \\n {{.Advises}}"
two = "Дам пару советов по стендапу: \\n {{.Advises}}"
